# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int



gpt-4-1106-preview:
    model_name: gpt4
    endpoints: null
    api_type: azure
    parallel: 8

{{MODEL_NAME}}:
    model_name: allenai/{{MODEL_NAME}}
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 8


