# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int



Meta-Llama-3.1-8B-base:
    model_name: /home/lidong1/jianglingjie/LLama-Factory/model_checkpoint/huggingface/Meta-Llama-3.1-8B
    endpoints: 
        - api_base: http://localhost:8000/v1
          api_key: token-abc123
    api_type: openai
    parallel: 8


