name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 2048
num_choices: 1

# a list of model to generate answers
model_list:
  - ta_rejected_llama3.1_instruct_dpo_2048
